import type { Metadata } from "next";
import { Chakra_Petch } from "next/font/google"; 
import "./globals.css";
import { GlobalProvider } from "@/components/globalvar/globalvariable";
import { Sidebar } from "@/components/sidebar";

const chakra = Chakra_Petch({
  subsets: ["latin", "thai"],
  weight: ["300", "400", "500", "600", "700"], 
});

export const metadata: Metadata = {
  title: "Web Application",
  description: "Generated by deefthanawat",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${chakra.className} antialiased`}>
        <GlobalProvider>
          <div className="h-dvh w-dvw flex"> 
            <Sidebar />
            {children}
          </div>
        </GlobalProvider>
      </body>
    </html>
  );
}
