import type { Metadata } from "next";
import { Chakra_Petch } from "next/font/google";
import "./globals.css";


const chakra = Chakra_Petch({
  subsets: ["latin", "thai"],
  weight: ["300", "400", "500", "600", "700"],
});

export const metadata: Metadata = {
  title: "Web Application",
  description: "Generated by deefthanawat", // ชื่อคุณจากไฟล์เดิม
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={`${chakra.className} antialiased`}>
        {children}
      </body>
    </html>
  );
}
